# Generated by Django 4.2.3 on 2023-07-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
