# Generated by Django 4.2.3 on 2023-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0004_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(upload_to='advertisement', verbose_name='Изображение'),
        ),
    ]
